# Site settings
title: Case Study Academy
description: A course on creating and using case studies to win more projects faster, for web dev agencies.
baseurl: "" # e.g. /docs if your site is hosted under a subpath
url: "https://casestudyacademy.com" # update to your custom domain or GitHub Pages URL
repository: wowashuwow/case-study-academy # GitHub repo, used for edit links and metadata

permalink: pretty

# Default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files that should not be part of the built site
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md

# Theme via remote_theme
remote_theme: just-the-docs/just-the-docs

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme features
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

enable_copy_code_button: true

heading_anchors: true

aux_links:
  "View source on GitHub":
    - "https://github.com/wowashuwow/case-study-academy"
aux_links_new_tab: true

nav_enabled: true
nav_sort: case_sensitive
nav_error_report: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2024 Case Study Academy.'

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/wowashuwow/case-study-academy"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

color_scheme: nil # Options: light (default), dark, or a custom scheme

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

mermaid:
  version: "9.1.6"
  # To load locally:
  # path: "/assets/js/mermaid.min.js"

# Markdown rendering options
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
